### PR TITLE
Fixed the on_message function and testing bot commands

### PR DESCRIPTION
**Pull request by jwim**
Hi, I am new to working on a open source project on github so this I am trying to test a pull request.

### CODE REVIEW

**Comment by jerbeck** [comment]
It looks like your missing some stuff that's in the current master branch.  Have you sync'd your fork with master?

**Comment by jwim** [comment]
> It looks like your missing some stuff that's in the current master branch. Have you sync'd your fork with master?

Yes, I was having issues updating my origin/master branch via git. But i was able to update it by creating an upstream repo and updating my master branch. I am now trying to correctly merge my feature branch with my origin/master branch so I can try and push onto my master branch with the merged version and do a pull request again.

**Comment by thereaper90917** [comment]
i went ahead and added your code. i however removed the "random" fix as it changed from on_message to a command a while ago. good job :)

**Comment by jwim** [comment]
Thanks!

**Pull request merged**
